title: Felipe Costa
author: Felipe Costa
email: 
description: >

include: ["_pages"]

# include:
#   - _pages/notes.md

header_pages:
  - _pages/about.md
  - _pages/posts.md
  - _pages/notes.md

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  # - jekyll-feed
  # - jekyll-redirect-from

minima_reboot:
  date_format: "%B %-d, %Y"
  date_format_short: "%b %-d"

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------

collections:
  notes:
    output: true
    permalink: /notes/:title/
  # projects:
  #   output: true
  #   permalink: /:collection/:title/
# - github.md

# footer_icons:
# - username: 
#   url: https://github.com/fe-lipe-c
#   icon: icon-github.svg

paginate: 5

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec

