title: Felipe Costa
author: Felipe Costa
email: 
description: >

plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  # - jekyll-feed
  # - jekyll-redirect-from

minima_reboot:
  date_format: "%B %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- posts.md
- cv.md
# - github.md

# footer_icons:
# - username: 
#   url: https://github.com/fe-lipe-c
#   icon: icon-github.svg

paginate: 5

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec

